ALTER TABLE gacha_products
  ADD COLUMN IF NOT EXISTS button_1 BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS button_10 BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS button_100 BOOLEAN NOT NULL DEFAULT TRUE;
