// ── 来世ガチャ（正一編）カード定義 ─────────────────────────────
import type { RaiseCardDef, RaiseDondenRoute } from './types';

/**
 * 正一編 13枚（ハズレ + ★1〜12）
 * ★1-2: mainSceneSteps=2, ★3-6: 3, ★7-10: 4, ★11-12: 5
 */
const SHOICHI_CARD_DEFS: RaiseCardDef[] = [
  {
    cardId: 'hazure',
    name: 'ハズレ',
    title: '何者にもなれなかった男',
    rarity: 'N',
    starLevel: 0,
    mainSceneSteps: 0,
    cardNumber: 'RS00',
    illustFile: 'shoichi_hazure.png',
    effectText: '夢破れし者が手にする一枚。だが、来世への希望は消えない。次こそ、運命を変えてみせる。',
    atk: 0,
    def: 0,
  },
  {
    cardId: 'c01',
    name: '魚',
    title: '海の住人',
    rarity: 'N',
    starLevel: 1,
    mainSceneSteps: 2,
    cardNumber: 'RS01',
    illustFile: 'shoichi_c01.png',
    effectText: '来世は魚。広い海を自由に泳ぎ回る。人間の悩みなど、波の彼方に消えてしまった。',
    atk: 400,
    def: 600,
  },
  {
    cardId: 'c02',
    name: 'ホームレス',
    title: '自由の代償',
    rarity: 'N',
    starLevel: 2,
    mainSceneSteps: 2,
    cardNumber: 'RS02',
    illustFile: 'shoichi_c02.png',
    effectText: '来世はホームレス。全てを失ったが、空は広く、風は自由だった。段ボールの城は、彼の王国。',
    atk: 300,
    def: 700,
  },
  {
    cardId: 'c03',
    name: 'ホスト',
    title: '夜の王子',
    rarity: 'R',
    starLevel: 3,
    mainSceneSteps: 3,
    cardNumber: 'RS03',
    illustFile: 'shoichi_c03.png',
    effectText: '来世はホスト。煌びやかな夜の世界で、言葉と笑顔だけを武器に戦う。No.1の座は、すぐそこに。',
    atk: 1100,
    def: 1000,
  },
  {
    cardId: 'c04',
    name: 'YouTuber',
    title: '配信の寵児',
    rarity: 'R',
    starLevel: 4,
    mainSceneSteps: 3,
    cardNumber: 'RS04',
    illustFile: 'shoichi_c04.png',
    effectText: '来世はYouTuber。カメラの前で繰り広げる破天荒な企画が、世界中のファンを熱狂させる。',
    atk: 1300,
    def: 1200,
  },
  {
    cardId: 'c05',
    name: '医者',
    title: '命を救う手',
    rarity: 'SR',
    starLevel: 5,
    mainSceneSteps: 3,
    cardNumber: 'RS05',
    illustFile: 'shoichi_c05.png',
    effectText: '来世は医者。人の命を預かる重責を背負いながら、一人でも多くの患者を救うために今日もメスを握る。',
    atk: 1700,
    def: 1600,
  },
  {
    cardId: 'c06',
    name: '弁護士',
    title: '正義の代弁者',
    rarity: 'SR',
    starLevel: 6,
    mainSceneSteps: 3,
    cardNumber: 'RS06',
    illustFile: 'shoichi_c06.png',
    effectText: '来世は弁護士。法廷で繰り広げる弁論は、聞く者全ての心を揺さぶる。正義は、言葉の中にある。',
    atk: 1900,
    def: 1700,
  },
  {
    cardId: 'c07',
    name: '政治家',
    title: '国を導く者',
    rarity: 'SSR',
    starLevel: 7,
    mainSceneSteps: 4,
    cardNumber: 'RS07',
    illustFile: 'shoichi_c07.png',
    effectText: '来世は政治家。清濁併せ呑む覚悟で、理想の国づくりに邁進する。その演説は、万人の心を動かす。',
    atk: 2400,
    def: 2100,
  },
  {
    cardId: 'c08',
    name: 'プロ野球選手',
    title: 'ダイヤモンドの英雄',
    rarity: 'SSR',
    starLevel: 8,
    mainSceneSteps: 4,
    cardNumber: 'RS08',
    illustFile: 'shoichi_c08.png',
    effectText: '来世はプロ野球選手。満塁のチャンスで打席に立つ。スタンドの歓声が、バットを振る力に変わる。',
    atk: 2700,
    def: 2300,
  },
  {
    cardId: 'c09',
    name: '映画監督',
    title: '夢を映す者',
    rarity: 'UR',
    starLevel: 9,
    mainSceneSteps: 4,
    cardNumber: 'RS09',
    illustFile: 'shoichi_c09.png',
    effectText: '来世は映画監督。スクリーンに映し出される物語は、観る者の人生を変える力を持つ。カット！もう一度。',
    atk: 3100,
    def: 2600,
  },
  {
    cardId: 'c10',
    name: 'ロックスター',
    title: '伝説のステージ',
    rarity: 'UR',
    starLevel: 10,
    mainSceneSteps: 4,
    cardNumber: 'RS10',
    illustFile: 'shoichi_c10.png',
    effectText: '来世はロックスター。10万人の前でギターを掻き鳴らす。その音は、世界の果てまで届く叫び。',
    atk: 3400,
    def: 2900,
  },
  {
    cardId: 'c11',
    name: '独裁者',
    title: '鉄の支配者',
    rarity: 'LR',
    starLevel: 11,
    mainSceneSteps: 5,
    cardNumber: 'RS11',
    illustFile: 'shoichi_c11.png',
    effectText: '来世は独裁者。絶対的な権力で国を支配する。恐れられ、崇められ、孤独の頂点に君臨する。',
    atk: 3900,
    def: 3600,
  },
  {
    cardId: 'c12',
    name: '巨額投資家',
    title: '世界経済の支配者',
    rarity: 'LR',
    starLevel: 12,
    mainSceneSteps: 5,
    cardNumber: 'RS12',
    illustFile: 'shoichi_c12.png',
    effectText: '来世は巨額投資家。一つの判断で世界経済が動く。その指先が触れるもの全てが黄金に変わる、最強の来世。',
    atk: 4500,
    def: 4000,
  },
];

/** 正一編 どんでん返しルート（11本） */
export const SHOICHI_DONDEN_ROUTES: RaiseDondenRoute[] = [
  { fromCardId: 'c01', toCardId: 'c05' },
  { fromCardId: 'c01', toCardId: 'c07' },
  { fromCardId: 'c02', toCardId: 'c06' },
  { fromCardId: 'c02', toCardId: 'c08' },
  { fromCardId: 'c03', toCardId: 'c09' },
  { fromCardId: 'c03', toCardId: 'c11' },
  { fromCardId: 'c04', toCardId: 'c08' },
  { fromCardId: 'c05', toCardId: 'c10' },
  { fromCardId: 'c06', toCardId: 'c11' },
  { fromCardId: 'c08', toCardId: 'c12' },
  // 11th route: additional path
  { fromCardId: 'c07', toCardId: 'c12' },
];

/** cardId → カード定義 */
export const SHOICHI_CARD_MAP = new Map<string, RaiseCardDef>(
  SHOICHI_CARD_DEFS.map((c) => [c.cardId, c]),
);

/** 全カード定義の配列 */
export const ALL_SHOICHI_CARDS = SHOICHI_CARD_DEFS;

/** ★レベルからカードを取得 */
export function getShoichiCardByStarLevel(starLevel: number): RaiseCardDef | undefined {
  return SHOICHI_CARD_DEFS.find((c) => c.starLevel === starLevel);
}
