// ── 来世ガチャ（健太編）カード定義 ─────────────────────────────
import type { RaiseCardDef, RaiseDondenRoute } from './types';

/**
 * 健太編 13枚（ハズレ + ★1〜12）
 * ★1-2: mainSceneSteps=2, ★3-6: 3, ★7-10: 4, ★11-12: 5
 */
const KENTA_CARD_DEFS: RaiseCardDef[] = [
  {
    cardId: 'hazure',
    name: 'ハズレ',
    title: '何者にもなれなかった男',
    rarity: 'N',
    starLevel: 0,
    mainSceneSteps: 0,
    cardNumber: 'RK00',
    illustFile: 'kenta_hazure.png',
    effectText: '夢破れし者が手にする一枚。だが、来世への希望は消えない。次こそ、運命を変えてみせる。',
    atk: 0,
    def: 0,
  },
  {
    cardId: 'c01',
    name: 'コンビニ夜勤',
    title: '深夜の番人',
    rarity: 'N',
    starLevel: 1,
    mainSceneSteps: 2,
    cardNumber: 'RK01',
    illustFile: 'kenta_c01.png',
    effectText: '来世はコンビニの夜勤スタッフ。レジ打ちと品出しの日々だが、深夜の静けさの中に小さな平穏を見つけた。',
    atk: 500,
    def: 400,
  },
  {
    cardId: 'c02',
    name: '引きこもり',
    title: '部屋の王',
    rarity: 'N',
    starLevel: 2,
    mainSceneSteps: 2,
    cardNumber: 'RK02',
    illustFile: 'kenta_c02.png',
    effectText: '来世は自室から出ない生活。だが、ネットの世界では誰よりも饒舌で、密かに影響力を持つ存在だった。',
    atk: 300,
    def: 800,
  },
  {
    cardId: 'c03',
    name: 'バンドマン',
    title: '路上の叫び',
    rarity: 'R',
    starLevel: 3,
    mainSceneSteps: 3,
    cardNumber: 'RK03',
    illustFile: 'kenta_c03.png',
    effectText: '来世はストリートで歌うバンドマン。夢を追い続ける姿に、通りすがりの人々が足を止める。',
    atk: 1200,
    def: 900,
  },
  {
    cardId: 'c04',
    name: '料理人',
    title: '炎の料理人',
    rarity: 'R',
    starLevel: 4,
    mainSceneSteps: 3,
    cardNumber: 'RK04',
    illustFile: 'kenta_c04.png',
    effectText: '来世は一流レストランの見習いシェフ。厳しい修行の果てに、自分だけの味を見つけ出した。',
    atk: 1400,
    def: 1100,
  },
  {
    cardId: 'c05',
    name: '探偵',
    title: '真実を暴く者',
    rarity: 'SR',
    starLevel: 5,
    mainSceneSteps: 3,
    cardNumber: 'RK05',
    illustFile: 'kenta_c05.png',
    effectText: '来世は私立探偵。誰もが見て見ぬふりをする闇に、一人で立ち向かう。真実だけが彼の味方だ。',
    atk: 1800,
    def: 1500,
  },
  {
    cardId: 'c06',
    name: 'プロゲーマー',
    title: '電脳の覇者',
    rarity: 'SR',
    starLevel: 6,
    mainSceneSteps: 3,
    cardNumber: 'RK06',
    illustFile: 'kenta_c06.png',
    effectText: '来世はプロゲーマー。世界大会の舞台で、その指先が奇跡を起こす。画面の向こうに広がる無限の可能性。',
    atk: 2000,
    def: 1600,
  },
  {
    cardId: 'c07',
    name: '格闘家',
    title: '不屈の拳',
    rarity: 'SSR',
    starLevel: 7,
    mainSceneSteps: 4,
    cardNumber: 'RK07',
    illustFile: 'kenta_c07.png',
    effectText: '来世は格闘家。何度倒れても立ち上がるその姿は、リングの外にいる全ての人に勇気を与えた。',
    atk: 2500,
    def: 2000,
  },
  {
    cardId: 'c08',
    name: '宇宙飛行士',
    title: '星を越える者',
    rarity: 'SSR',
    starLevel: 8,
    mainSceneSteps: 4,
    cardNumber: 'RK08',
    illustFile: 'kenta_c08.png',
    effectText: '来世は宇宙飛行士。地球を離れた瞬間、全ての悩みがちっぽけに見えた。星の海に浮かぶ、孤独で壮大な冒険。',
    atk: 2800,
    def: 2200,
  },
  {
    cardId: 'c09',
    name: '革命家',
    title: '世界を変える者',
    rarity: 'UR',
    starLevel: 9,
    mainSceneSteps: 4,
    cardNumber: 'RK09',
    illustFile: 'kenta_c09.png',
    effectText: '来世は革命家。不条理な世界に抗い、民衆の先頭に立つ。その言葉は、時代そのものを動かす力を持つ。',
    atk: 3200,
    def: 2500,
  },
  {
    cardId: 'c10',
    name: '大富豪',
    title: '黄金の帝王',
    rarity: 'UR',
    starLevel: 10,
    mainSceneSteps: 4,
    cardNumber: 'RK10',
    illustFile: 'kenta_c10.png',
    effectText: '来世は大富豪。金で買えないものはないと豪語するが、本当に欲しいのは、かつて失った温もりだった。',
    atk: 3500,
    def: 2800,
  },
  {
    cardId: 'c11',
    name: '魔王',
    title: '闇を統べる者',
    rarity: 'LR',
    starLevel: 11,
    mainSceneSteps: 5,
    cardNumber: 'RK11',
    illustFile: 'kenta_c11.png',
    effectText: '来世は魔王。全てを支配する力を手にしたが、玉座から見える景色はどこまでも孤独だった。それでも、この力で守れるものがある。',
    atk: 4000,
    def: 3500,
  },
  {
    cardId: 'c12',
    name: '勇者',
    title: '希望の光',
    rarity: 'LR',
    starLevel: 12,
    mainSceneSteps: 5,
    cardNumber: 'RK12',
    illustFile: 'kenta_c12.png',
    effectText: '来世は勇者。伝説に語られるその名は、絶望の淵に立つ全ての者に希望を与える。最強の来世、ここに誕生。',
    atk: 4500,
    def: 4000,
  },
];

/** 健太編 どんでん返しルート（10本） */
export const KENTA_DONDEN_ROUTES: RaiseDondenRoute[] = [
  { fromCardId: 'c01', toCardId: 'c05' },
  { fromCardId: 'c01', toCardId: 'c07' },
  { fromCardId: 'c02', toCardId: 'c06' },
  { fromCardId: 'c02', toCardId: 'c08' },
  { fromCardId: 'c03', toCardId: 'c10' },
  { fromCardId: 'c04', toCardId: 'c09' },
  { fromCardId: 'c05', toCardId: 'c08' },
  { fromCardId: 'c06', toCardId: 'c09' },
  { fromCardId: 'c07', toCardId: 'c11' },
  { fromCardId: 'c08', toCardId: 'c12' },
];

/** cardId → カード定義 */
export const KENTA_CARD_MAP = new Map<string, RaiseCardDef>(
  KENTA_CARD_DEFS.map((c) => [c.cardId, c]),
);

/** 全カード定義の配列 */
export const ALL_KENTA_CARDS = KENTA_CARD_DEFS;

/** ★レベルからカードを取得 */
export function getKentaCardByStarLevel(starLevel: number): RaiseCardDef | undefined {
  return KENTA_CARD_DEFS.find((c) => c.starLevel === starLevel);
}
